enum CONSTANT {
    FIELD_ENITY = "FIELD_ENITY",
    FIELD_COLUMN = "FIELD_COLUMN",
    SYMBOL_BRACES_FRONT = "SYMBOL_BRACES_FRONT",
    SYMBOL_BRACES_REAR = "SYMBOL_BRACES_REAR",
    SYMBOL_COMMA = "SYMBOL_COMMA",
    PROGRAM = "PROGRAM",
    NUMBER="NUMBER",
    LETTER="LETTER"
}
const REGULAR = {
    isEnityField: /^[A-Z]+[a-zA-Z0-9_]+[a-z]+$/
}
export {
    CONSTANT,REGULAR
}